# Numpy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0:4]

array([0, 1, 2, 3])

In [6]:
arr[3:4]

array([3])

In [7]:
arr[:4]

array([0, 1, 2, 3])

In [8]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[:1] = 100

In [11]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [16]:
slice_of_arr = arr[1:3]

In [17]:
slice_of_arr

array([1, 2])

In [18]:
slice_of_arr[:] = 100

In [19]:
slice_of_arr

array([100, 100])

In [20]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [21]:
arr_copy = arr.copy()

In [22]:
arr_copy

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [25]:
arr_copy[:3] = np.arange(0, 3)

In [26]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [31]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d[1][2]

30

In [33]:
arr_2d[1, 2]

30

In [36]:
arr_2d[1:2, :]

array([[20, 25, 30]])

In [37]:
arr = np.arange(11)

In [39]:
arr[arr > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [40]:
arr_2d = np.arange(50).reshape(5, 10)

In [41]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])