# Numpy Arrays

In [2]:
my_list = [1, 2, 3]

In [3]:
my_list

[1, 2, 3]

In [5]:
import numpy as nb

In [7]:
nb.array(my_list)

array([1, 2, 3])

In [9]:
my_mat =  [[1, 2 ,3], [4, 5, 6], [7, 8, 9]]

In [10]:
arr = nb.array(my_mat)

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.zeros(4)

NameError: name 'np' is not defined

In [13]:
 nb.zeros(4)

array([0., 0., 0., 0.])

In [14]:
nb.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
nb.twos(2, 3)

AttributeError: module 'numpy' has no attribute 'twos'

In [16]:
nb.random.rand(2)

array([0.19645098, 0.46937823])

In [17]:
nb.random.randn(2)

array([1.24862946, 0.57385957])

In [18]:
nb.random.randn(5)

array([ 0.06883049, -1.02540099,  0.51162024,  0.22534066,  1.43879981])

In [19]:
arr = nb.arange(25)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr.reshape(2, 5)

ValueError: cannot reshape array of size 25 into shape (2,5)